# Generated by Django 2.0.1 on 2018-01-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPlatform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(blank=True, default='', max_length=254, null=True, unique=True, verbose_name='Enlace a código fuente'),
        ),
    ]
