# Generated by Django 2.0.1 on 2018-01-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webPlatform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nombre',
            new_name='name',
        ),
    ]
