# Generated by Django 2.0.1 on 2018-01-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPlatform', '0002_auto_20180113_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='use_library',
            field=models.BooleanField(default=True, verbose_name='¿Utiliza Librería BeBot?'),
        ),
    ]
